/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'teal-dark': '#0B4F6C',
        'teal-mid': '#1A7A9A',
        'teal-light': '#D0EAF2',
        coral: '#E8734A',
        cream: '#F7F3EE',
        'provider-green': '#2D9E6B',
        'admin-purple': '#2D1B69',
        warning: '#F59E0B',
        error: '#E53E3E',
        'text-dark': '#1A1A2E',
        'text-mid': '#4A5568',
        'text-light': '#A0AEC0',
        border: '#E8E0D6',
      },
      fontFamily: {
        display: ['Sora-ExtraBold'],
        heading: ['Sora-Bold'],
        subheading: ['Sora-SemiBold'],
        body: ['DMSans-Regular'],
        'body-medium': ['DMSans-Medium'],
        caption: ['DMSans-Bold'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px' }],
        'display-sm': ['28px', { lineHeight: '36px' }],
        h1: ['22px', { lineHeight: '28px' }],
        h2: ['18px', { lineHeight: '24px' }],
        h3: ['16px', { lineHeight: '22px' }],
        body: ['14px', { lineHeight: '20px' }],
        caption: ['13px', { lineHeight: '18px' }],
        label: ['11px', { lineHeight: '14px' }],
      },
      spacing: {
        1: '4px',
        2: '8px',
        2.5: '10px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
      borderRadius: {
        xs: '6px',
        sm: '10px',
        md: '16px',
        lg: '20px',
        xl: '28px',
        full: '999px',
      },
      boxShadow: {
        card: '0px 2px 12px rgba(10,79,107,0.08)',
      },
    },
  },
  plugins: [],
};
